root = "."
tmp_dir = "tmp"

[build]
cmd = "swag init -g ./src/cmd/api/app.go -o ./docs && go build -o ./tmp/main ./src/cmd/api"
bin = "tmp/main"
delay = 1000

include_ext = ["go"]
exclude_dir = ["vendor", "tmp"]

log = "air.log"

[log]
color = true

